Imports System.Text
Imports System.Linq

Public Class CGenerator
    Private _parser As RpgParser

    Public Sub New(parser As RpgParser)
        _parser = parser
    End Sub

    Public Function Generate() As String
        Dim sb As New StringBuilder()

        ' Headers - Use RPG Runtime Library
        sb.AppendLine("/*")
        sb.AppendLine(" * Generated by RPG2C Transpiler")
        sb.AppendLine(" * Using RPG Runtime Library v1.0")
        sb.AppendLine(" */")
        sb.AppendLine()
        sb.AppendLine("#include <stdio.h>")
        sb.AppendLine("#include <stdlib.h>")
        sb.AppendLine("#include <string.h>")
        sb.AppendLine("#include <stdbool.h>")
        sb.AppendLine("#include ""rpg_runtime.h""")
        sb.AppendLine("#include ""rpg_file.h""")
        sb.AppendLine("#include ""rpg_data.h""")
        sb.AppendLine()

        ' State variables - use extern declarations (defined in rpg_runtime.c)
        sb.AppendLine("// --- Indicators (extern from runtime) ---")
        sb.AppendLine("extern bool IND[100];")
        sb.AppendLine("extern bool IN_LR;")
        sb.AppendLine("extern bool IN_1P;")
        sb.AppendLine("extern bool IN_MR;")
        sb.AppendLine("extern bool IN_L[10];")
        sb.AppendLine("#define IN_L1 IN_L[1] ")
        sb.AppendLine("#define IN_L2 IN_L[2] ")
        sb.AppendLine("#define IN_L3 IN_L[3] ")
        sb.AppendLine("#define IN_L4 IN_L[4] ")
        sb.AppendLine("#define IN_L5 IN_L[5] ")
        sb.AppendLine("#define IN_L6 IN_L[6] ")
        sb.AppendLine("#define IN_L7 IN_L[7] ")
        sb.AppendLine("#define IN_L8 IN_L[8] ")
        sb.AppendLine("#define IN_L9 IN_L[9] ")
        sb.AppendLine()

        sb.AppendLine("// --- Program Variables ---")
        Dim vars = GetVariables()
        For Each v In vars.Values
            If v.IsNumeric Then
                sb.AppendLine($"double {v.Name} = 0.0;")
            Else
                sb.AppendLine($"char {v.Name}[{v.Length + 1}] = {{0}};")
            End If
        Next
        
        ' Previous Value variables for Level Breaks
        sb.AppendLine("// --- Control Level Buffers ---")
        For Each iSpec In _parser.InputSpecs.Where(Function(is_l) Not is_l.IsRecordLine AndAlso Not String.IsNullOrEmpty(is_l.ControlLevel))
            Dim v = vars(iSpec.FieldName)
            If v.IsNumeric Then
                sb.AppendLine($"double PREV_{iSpec.FieldName} = 0.0;")
            Else
                sb.AppendLine($"char PREV_{iSpec.FieldName}[{v.Length + 1}] = {{0}};")
            End If
        Next
        sb.AppendLine()

        ' Generate Subroutines BEFORE main
        sb.AppendLine("// --- Subroutines ---")
        Dim inSR = False
        For Each c In _parser.CalcSpecs
            If c.Opcode = "BEGSR" Then
                inSR = True
                sb.AppendLine($"void {c.Factor1.Trim()}() {{")
            ElseIf c.Opcode = "ENDSR" Then
                sb.AppendLine("}")
                sb.AppendLine()
                inSR = False
            ElseIf inSR Then
                GenerateCalcOp(sb, c, vars, "    ")
            End If
        Next

        ' Function Signature
        sb.AppendLine("int main(int argc, char** argv) {")
        sb.AppendLine("    // Initialize RPG runtime")
        sb.AppendLine("    rpg_init();")
        sb.AppendLine()
        
        ' File Setup
        Dim files = _parser.FileSpecs.GroupBy(Function(f_l) f_l.Filename).Select(Function(g_l) g_l.First()).ToList()
        Dim expectedArgs = files.Count + 1
        
        sb.AppendLine($"    if (argc < {expectedArgs}) {{")
        sb.Append("        printf(""Usage: %s ")
        For Each f In files
            sb.Append($"<{f.Filename}> ")
        Next
        sb.AppendLine("\n"", argv[0]);")
        sb.AppendLine("        return 1;")
        sb.AppendLine("    }")
        sb.AppendLine()

        Dim fileIndex = 1
        Dim inFileData As FileSpec = Nothing
        Dim outFileData As FileSpec = Nothing
        
        For Each f In files
            If f.FileType = "I" Then
                inFileData = f
                sb.AppendLine($"    FILE* {f.Filename} = fopen(argv[{fileIndex}], ""r"");")
                sb.AppendLine($"    if (!{f.Filename}) {{ printf(""Failed to open {f.Filename}\n""); return 1; }}")
            ElseIf f.FileType = "O" Then
                outFileData = f
                sb.AppendLine($"    FILE* {f.Filename} = fopen(argv[{fileIndex}], ""w"");")
                sb.AppendLine($"    if (!{f.Filename}) {{ printf(""Failed to open {f.Filename}\n""); return 1; }}")
            End If
            fileIndex += 1
        Next
        sb.AppendLine()
        
        If inFileData IsNot Nothing Then
            Dim recLen = If(inFileData.RecordLength > 0, inFileData.RecordLength, 80)
            sb.AppendLine($"    char recordBuf[{recLen + 10}];")
            sb.AppendLine($"    char lineIn[1024];")
        End If
        sb.AppendLine("    bool firstRecord = true;")
        sb.AppendLine()

        ' Print 1P Headers before loop
        sb.AppendLine("    // --- 1P Header Processing ---")
        sb.AppendLine("    IN_1P = true;")
        GenerateOutput(sb, vars, "H", "    ")
        sb.AppendLine()

        ' RPG Logic Cycle Loop
        sb.AppendLine("    // --- Main Logic Cycle ---")
        If inFileData IsNot Nothing Then
            Dim recLen = If(inFileData.RecordLength > 0, inFileData.RecordLength, 80)
            sb.AppendLine($"    while (fgets(lineIn, sizeof(lineIn), {inFileData.Filename})) {{")
            sb.AppendLine("        // Prepare fixed-length buffer from line")
            sb.AppendLine("        memset(recordBuf, ' ', sizeof(recordBuf));")
            sb.AppendLine("        int len = strlen(lineIn);")
            sb.AppendLine("        while(len > 0 && (lineIn[len-1] == '\n' || lineIn[len-1] == '\r')) len--;")
            sb.AppendLine($"        strncpy(recordBuf, lineIn, (len > {recLen}) ? {recLen} : len);")
            sb.AppendLine($"        recordBuf[{recLen}] = 0;")
            sb.AppendLine("        IN_1P = false;")
            
            ' 1. Check for Level Breaks
            sb.AppendLine("        // Check for Level Breaks")
            For Each iSpec In _parser.InputSpecs.Where(Function(ispec_l) Not ispec_l.IsRecordLine AndAlso Not String.IsNullOrEmpty(ispec_l.ControlLevel))
                Dim v = vars(iSpec.FieldName)
                Dim len = iSpec.EndPos - iSpec.StartPos + 1
                sb.AppendLine($"        {{")
                sb.AppendLine($"            char cur_val[{len + 1}];")
                sb.AppendLine($"            strncpy(cur_val, recordBuf + {iSpec.StartPos - 1}, {len}); cur_val[{len}] = 0;")
                If v.IsNumeric Then
                    If iSpec.DataType = "P" Then
                        sb.AppendLine($"            double d_cur = rpg_decode_packed((const unsigned char*)recordBuf, {iSpec.StartPos - 1}, {len}, {If(String.IsNullOrEmpty(iSpec.DecimalPos), 0, iSpec.DecimalPos)});")
                    Else
                        sb.AppendLine($"            double d_cur = atof(cur_val);")
                    End If
                    sb.AppendLine($"            if (!firstRecord && d_cur != PREV_{iSpec.FieldName}) IN_L[{(If(iSpec.ControlLevel.StartsWith("L"), iSpec.ControlLevel.Substring(1), "0"))}] = true;")
                Else
                    sb.AppendLine($"            if (!firstRecord && strcmp(cur_val, PREV_{iSpec.FieldName}) != 0) IN_L[{(If(iSpec.ControlLevel.StartsWith("L"), iSpec.ControlLevel.Substring(1), "0"))}] = true;")
                End If
            Next

            ' 2. Total Calcs
            sb.AppendLine()
            sb.AppendLine("        if (!firstRecord && (")
            Dim totalConds = New List(Of String)
            For i As Integer = 1 To 9
                totalConds.Add($"IN_L{i}")
            Next
            totalConds.Add("IN_LR")
            sb.AppendLine("            " & String.Join(" || ", totalConds))
            sb.AppendLine("        )) {")
            sb.AppendLine("            // --- Total Calculations ---")
            For Each c In _parser.CalcSpecs.Where(Function(cs_l) cs_l.ControlLevel.StartsWith("L") OrElse cs_l.ControlLevel = "LR")
                GenerateCalcOp(sb, c, vars, "            ")
            Next
            sb.AppendLine()
            sb.AppendLine("            // --- Total Output ---")
            GenerateOutput(sb, vars, "T")
            sb.AppendLine("        }")

            ' Reset Level Indicators
            sb.AppendLine("        for(int i=1; i<10; i++) IN_L[i] = false;")
            sb.AppendLine()

            ' 3. Extract Input Fields and Update PREV buffers
            sb.AppendLine("        // Extract Input Fields")
            For Each iSpec In _parser.InputSpecs.Where(Function(ispec_l) Not ispec_l.IsRecordLine)
                Dim v = vars(iSpec.FieldName)
                Dim len = iSpec.EndPos - iSpec.StartPos + 1
                sb.AppendLine($"        {{")
                sb.AppendLine($"            char tmp[{len+1}]; strncpy(tmp, recordBuf + {iSpec.StartPos - 1}, {len}); tmp[{len}] = 0;")
                If v.IsNumeric Then
                    If iSpec.DataType = "P" Then
                        sb.AppendLine($"            {iSpec.FieldName} = rpg_decode_packed((const unsigned char*)recordBuf, {iSpec.StartPos - 1}, {len}, {If(String.IsNullOrEmpty(iSpec.DecimalPos), 0, iSpec.DecimalPos)});")
                    Else
                        sb.AppendLine($"            {iSpec.FieldName} = atof(tmp);")
                    End If
                    If Not String.IsNullOrEmpty(iSpec.ControlLevel) Then sb.AppendLine($"            PREV_{iSpec.FieldName} = {iSpec.FieldName};")
                Else
                    sb.AppendLine($"            strcpy({iSpec.FieldName}, tmp);")
                    If Not String.IsNullOrEmpty(iSpec.ControlLevel) Then sb.AppendLine($"            strcpy(PREV_{iSpec.FieldName}, {iSpec.FieldName});")
                End If
                sb.AppendLine($"        }}")
            Next

            sb.AppendLine()
            sb.AppendLine("        // --- Detail Calculations ---")
            For Each cSpec In _parser.CalcSpecs.Where(Function(cs_l) String.IsNullOrWhiteSpace(cs_l.ControlLevel) AndAlso Not IsInSubroutine(cs_l))
                GenerateCalcOp(sb, cSpec, vars, "        ")
            Next

            sb.AppendLine()
            sb.AppendLine("        // --- Detail Output ---")
            GenerateOutput(sb, vars, "D")
            
            sb.AppendLine("        firstRecord = false;")
            sb.AppendLine("        if (IN_LR) break;")
            sb.AppendLine("    }")
        Else
            ' No input file, run once
            sb.AppendLine("    {")
            sb.AppendLine("        IN_LR = true;")
            sb.AppendLine("        // Detail Calculations")
            For Each cSpec In _parser.CalcSpecs.Where(Function(cs_l) String.IsNullOrWhiteSpace(cs_l.ControlLevel) AndAlso Not IsInSubroutine(cs_l))
                GenerateCalcOp(sb, cSpec, vars, "        ")
            Next
            GenerateOutput(sb, vars, "D", "        ")
            sb.AppendLine("    }")
        End If

        sb.AppendLine()
        sb.AppendLine("    // --- Final LR Cycle ---")
        sb.AppendLine("    IN_LR = true;")
        sb.AppendLine("    // Total Calculations")
        For Each c In _parser.CalcSpecs.Where(Function(cs_l) cs_l.ControlLevel = "LR" OrElse (cs_l.ControlLevel.StartsWith("L") AndAlso cs_l.ControlLevel <> "L0"))
            GenerateCalcOp(sb, c, vars, "    ")
        Next
        sb.AppendLine("    // Total Output")
        GenerateOutput(sb, vars, "T")

        ' Cleanup
        For Each f In files
            sb.AppendLine($"    if ({f.Filename}) fclose({f.Filename});")
        Next

        sb.AppendLine()
        sb.AppendLine("    // Cleanup RPG runtime")
        sb.AppendLine("    rpg_cleanup();")
        sb.AppendLine("    return 0;")
        sb.AppendLine("}")
        
        ' Add initial header processing if requested outside loop (simplified)
        sb.AppendLine()
        
        Return sb.ToString()
    End Function

    Private Function GetIndicatorRef(ind As String) As String
        If String.IsNullOrEmpty(ind) Then Return "true"
        Dim upper = ind.ToUpper()
        If upper = "LR" Then Return "IN_LR"
        If upper = "1P" Then Return "IN_1P"
        If upper = "L1" Then Return "IN_L1"
        If upper.StartsWith("L") AndAlso upper.Length = 2 Then Return $"IN_L[{upper.Substring(1)}]"
        
        Dim val As Integer
        If Integer.TryParse(ind, val) Then Return $"IND[{val}]"
        Return "false"
    End Function

    Private Sub GenerateOutput(sb As StringBuilder, vars As Dictionary(Of String, VariableDef), type As String, Optional indent As String = "            ")
        Dim currentOutFile = ""
        Dim currentType = ""
        Dim lastPos = 0

        For Each oSpec In _parser.OutputSpecs
            If oSpec.IsRecordLine Then
                ' Handle newlines from PREVIOUS record if any
                ' (Actually RPG does spacing BEFORE the line usually, but SpaceAfter is common)
                
                currentOutFile = oSpec.Filename
                currentType = oSpec.Type
                
                If (currentType = type OrElse type = "*ALL") Then
                    lastPos = 0
                End If
            Else
                If Not String.IsNullOrEmpty(currentOutFile) AndAlso (currentType = type OrElse type = "*ALL") Then
                    ' Simple conditioning
                    Dim indCondition = ""
                    If Not String.IsNullOrEmpty(oSpec.OutputIndicator1) Then
                        indCondition = $"if ({GetIndicatorRef(oSpec.OutputIndicator1)}) "
                    End If

                    Dim gap = oSpec.EndPos - lastPos
                    Dim content = ""
                    Dim printLen = 0

                    If Not String.IsNullOrEmpty(oSpec.FieldName) Then
                        If vars.ContainsKey(oSpec.FieldName) Then
                            Dim v = vars(oSpec.FieldName)
                            printLen = v.Length
                            If v.IsNumeric Then
                                If Not String.IsNullOrEmpty(oSpec.EditCode) Then
                                    sb.AppendLine($"{indent}{indCondition}{{ char buf[64]; rpg_format_edit(buf, {v.Name}, '{oSpec.EditCode}', {v.Length}, {v.DecimalPos}); fprintf({currentOutFile}, ""%*s%s"", {(gap - printLen)}, """", buf); }}")
                                Else
                                    sb.AppendLine($"{indent}{indCondition}fprintf({currentOutFile}, ""%*s%-*.*f"", {(gap - printLen)}, """", {v.Length}, {v.DecimalPos}, {v.Name});")
                                End If
                            Else
                                sb.AppendLine($"{indent}{indCondition}fprintf({currentOutFile}, ""%*s%-*s"", {(gap - printLen)}, """", {v.Length}, {v.Name});")
                            End If
                        End If
                    ElseIf Not String.IsNullOrEmpty(oSpec.Constant) Then
                        Dim sanitized = oSpec.Constant.Replace("'", "")
                        printLen = sanitized.Length
                        sb.AppendLine($"{indent}{indCondition}fprintf({currentOutFile}, ""%*s%s"", {(gap - printLen)}, """", ""{sanitized}"");")
                    End If
                    
                    lastPos = oSpec.EndPos
                End If
            End If
            
            ' Add newline if this was the last spec for a record or next line is a new record
            Dim nextIndex = _parser.OutputSpecs.IndexOf(oSpec) + 1
            If (nextIndex >= _parser.OutputSpecs.Count OrElse _parser.OutputSpecs(nextIndex).IsRecordLine) AndAlso Not oSpec.IsRecordLine Then
                If Not String.IsNullOrEmpty(currentOutFile) AndAlso (currentType = type OrElse type = "*ALL") Then
                    sb.AppendLine($"{indent}fprintf({currentOutFile}, ""\n"");")
                End If
            End If
        Next
    End Sub

    Private Sub GenerateCalcOp(sb As StringBuilder, c As CalcSpec, vars As Dictionary(Of String, VariableDef), Optional indent As String = "        ")
        ' Handle TAG/Labels
        If c.Opcode = "TAG" Then
            sb.AppendLine($"{c.Factor1}:;")
            Return
        End If

        ' Handle conditioning indicators (Up to 3)
        Dim conditions As New List(Of String)
        If Not String.IsNullOrWhiteSpace(c.Indicator1) Then
            conditions.Add(If(c.Not1, "!", "") & $"IND[{c.Indicator1}]")
        End If
        If Not String.IsNullOrWhiteSpace(c.Indicator2) Then
            conditions.Add(If(c.Not2, "!", "") & $"IND[{c.Indicator2}]")
        End If
        If Not String.IsNullOrWhiteSpace(c.Indicator3) Then
            conditions.Add(If(c.Not3, "!", "") & $"IND[{c.Indicator3}]")
        End If

        Dim condWrapper = False
        If conditions.Count > 0 Then
            sb.AppendLine($"{indent}if ({String.Join(" && ", conditions)}) {{")
            indent &= "    "
            condWrapper = True
        End If

        ' Extract components
        Dim f1 = c.Factor1.Trim()
        Dim f2 = c.Factor2.Trim()
        Dim res = c.ResultField.Trim()

        Select Case c.Opcode
            Case "ADD"
                Dim addVal = If(String.IsNullOrEmpty(f1), res, f1)
                If Not String.IsNullOrEmpty(c.DecimalPos) AndAlso c.DecimalPos.Contains("H") Then
                    sb.AppendLine($"{indent}{res} = rpg_half_adjust({addVal} + {f2}, {c.DecimalPos.Replace("H", "")});")
                Else
                    sb.AppendLine($"{indent}{res} = {addVal} + {f2};")
                End If
            Case "SUB"
                Dim subVal = If(String.IsNullOrEmpty(f1), res, f1)
                If Not String.IsNullOrEmpty(c.DecimalPos) AndAlso c.DecimalPos.Contains("H") Then
                    sb.AppendLine($"{indent}{res} = rpg_half_adjust({subVal} - {f2}, {c.DecimalPos.Replace("H", "")});")
                Else
                    sb.AppendLine($"{indent}{res} = {subVal} - {f2};")
                End If
            Case "MULT"
                Dim multVal = If(String.IsNullOrEmpty(f1), res, f1)
                If Not String.IsNullOrEmpty(c.DecimalPos) AndAlso c.DecimalPos.Contains("H") Then
                    sb.AppendLine($"{indent}{res} = rpg_half_adjust({multVal} * {f2}, {c.DecimalPos.Replace("H", "")});")
                Else
                    sb.AppendLine($"{indent}{res} = {multVal} * {f2};")
                End If
            Case "DIV"
                Dim divVal = If(String.IsNullOrEmpty(f1), res, f1)
                If Not String.IsNullOrEmpty(c.DecimalPos) AndAlso c.DecimalPos.Contains("H") Then
                    sb.AppendLine($"{indent}if ({f2} != 0) {res} = rpg_half_adjust({divVal} / {f2}, {c.DecimalPos.Replace("H", "")});")
                Else
                    sb.AppendLine($"{indent}if ({f2} != 0) {res} = {divVal} / {f2};")
                End If
            Case "MVR"
                ' Move remainder from last division
                sb.AppendLine($"{indent}{res} = rpg_mvr({f1}, {f2});")
            Case "SQRT"
                ' Square root - Factor1 contains the value
                sb.AppendLine($"{indent}{res} = rpg_sqrt({f1});")
            Case "Z-ADD"
                sb.AppendLine($"{indent}{res} = {f2};")
            Case "MOVE", "MOVEL"
                If vars.ContainsKey(res) AndAlso Not vars(res).IsNumeric Then
                    Dim src = If(vars.ContainsKey(f2) OrElse Not f2.StartsWith("'"), f2, f2.Replace("'", """"))
                    ' String assignment
                    If src.StartsWith("""") Then
                        If c.Opcode = "MOVEL" Then
                            sb.AppendLine($"{indent}strncpy({res}, {src}, sizeof({res}) - 1);")
                        Else
                            sb.AppendLine($"{indent}strcpy({res}, {src});")
                        End If
                    Else
                        If c.Opcode = "MOVEL" Then
                            sb.AppendLine($"{indent}strncpy({res}, {f2}, sizeof({res}) - 1);")
                        Else
                            sb.AppendLine($"{indent}strcpy({res}, {f2});")
                        End If
                    End If
                Else
                    ' Numeric assignment
                    sb.AppendLine($"{indent}{res} = {f2};")
                End If
            Case "CAT"
                ' Concatenate strings
                Dim blanks = If(String.IsNullOrEmpty(c.FieldLength.ToString()), "0", c.FieldLength.ToString())
                sb.AppendLine($"{indent}rpg_cat({res}, {f1}, {f2}, {blanks});")
            Case "SUBST"
                ' Extract substring - Factor1=start, Factor2=length
                sb.AppendLine($"{indent}rpg_subst({res}, {res}, {f1}, {f2});")
            Case "SCAN"
                ' Scan for substring - Factor1=search string, Factor2=source string
                Dim resultInd = c.ResultingIndicatorEq.Trim()
                sb.AppendLine($"{indent}{res} = rpg_scan({f1}, {f2}, 1);")
                If resultInd <> "" Then
                    sb.AppendLine($"{indent}IND[{resultInd}] = ({res} > 0);")
                End If
            Case "XLATE"
                ' Translate characters - Factor1=from, Factor2=to
                sb.AppendLine($"{indent}rpg_xlate({res}, {res}, {f1}, {f2});")
            Case "TRIM"
                ' Trim trailing blanks
                sb.AppendLine($"{indent}rpg_trim({res}, {res});")
            Case "TRIML"
                ' Trim leading blanks
                sb.AppendLine($"{indent}rpg_triml({res}, {res});")
            Case "TRIMB"
                ' Trim both leading and trailing blanks
                sb.AppendLine($"{indent}rpg_trimb({res}, {res});")
            Case "LOOKUP"
                ' Lookup in array - Factor1=key, Factor2=array
                Dim foundInd = c.ResultingIndicatorEq.Trim()
                sb.AppendLine($"{indent}{{ int idx = rpg_lookup({f2}, sizeof({f2})/sizeof({f2}[0]), sizeof({f2}[0]), &{f1}, compare_func); ")
                sb.AppendLine($"{indent}  {res} = (idx >= 0) ? idx + 1 : 0;")
                If foundInd <> "" Then
                    sb.AppendLine($"{indent}  IND[{foundInd}] = (idx >= 0);")
                End If
                sb.AppendLine($"{indent}}}")
            Case "XFOOT"
                ' Sum array (cross-foot) - Factor2=array
                sb.AppendLine($"{indent}{res} = rpg_xfoot({f2}, sizeof({f2})/sizeof({f2}[0]));")
            Case "SORTA"
                ' Sort array - Factor2=array
                sb.AppendLine($"{indent}rpg_sorta({f2}, sizeof({f2})/sizeof({f2}[0]), sizeof({f2}[0]), compare_func);")
            Case "MOVEA"
                ' Move array - Factor1=source, Result=destination
                sb.AppendLine($"{indent}rpg_movea({res}, {f1}, sizeof({f1})/sizeof({f1}[0]), sizeof({f1}[0]));")
            Case "COMP"
                ' Sets indicators HI, LO, EQ
                Dim hi = c.ResultingIndicatorHi.Trim()
                Dim lo = c.ResultingIndicatorLo.Trim()
                Dim eq = c.ResultingIndicatorEq.Trim()
                If hi <> "" Then sb.AppendLine($"{indent}IND[{hi}] = ({f1} > {f2});")
                If lo <> "" Then sb.AppendLine($"{indent}IND[{lo}] = ({f1} < {f2});")
                If eq <> "" Then sb.AppendLine($"{indent}IND[{eq}] = ({f1} == {f2});")
            Case "SETON"
                Dim hi = c.ResultingIndicatorHi.Trim()
                Dim lo = c.ResultingIndicatorLo.Trim()
                Dim eq = c.ResultingIndicatorEq.Trim()
                If hi <> "" AndAlso hi <> "LR" Then sb.AppendLine($"{indent}IND[{hi}] = true;")
                If lo <> "" AndAlso lo <> "LR" Then sb.AppendLine($"{indent}IND[{lo}] = true;")
                If eq <> "" AndAlso eq <> "LR" Then sb.AppendLine($"{indent}IND[{eq}] = true;")
                If hi = "LR" OrElse lo = "LR" OrElse eq = "LR" Then sb.AppendLine($"{indent}IN_LR = true;")
            Case "SETOF"
                Dim hi = c.ResultingIndicatorHi.Trim()
                Dim lo = c.ResultingIndicatorLo.Trim()
                Dim eq = c.ResultingIndicatorEq.Trim()
                If hi <> "" AndAlso hi <> "LR" Then sb.AppendLine($"{indent}IND[{hi}] = false;")
                If lo <> "" AndAlso lo <> "LR" Then sb.AppendLine($"{indent}IND[{lo}] = false;")
                If eq <> "" AndAlso eq <> "LR" Then sb.AppendLine($"{indent}IND[{eq}] = false;")
            Case "GOTO"
                sb.AppendLine($"{indent}goto {f2};")
            Case "EXSR"
                sb.AppendLine($"{indent}{f2}();")
            Case "EXCPT"
                sb.AppendLine($"{indent}// EXCPT (External Output) unsupported in simplified generator")
        End Select

        If condWrapper Then
            indent = indent.Substring(0, indent.Length - 4)
            sb.AppendLine($"{indent}}}")
        End If
    End Sub

    Private Function IsInSubroutine(c As CalcSpec) As Boolean
        Dim inSR = False
        For Each cs In _parser.CalcSpecs
            If cs Is c Then Return inSR
            If cs.Opcode = "BEGSR" Then inSR = True
            If cs.Opcode = "ENDSR" Then inSR = False
        Next
        Return False
    End Function

    Private Function GetVariables() As Dictionary(Of String, VariableDef)
        Dim vars As New Dictionary(Of String, VariableDef)()

        ' From Input Specs
        For Each i In _parser.InputSpecs
            If Not i.IsRecordLine AndAlso Not String.IsNullOrWhiteSpace(i.FieldName) Then
                If Not vars.ContainsKey(i.FieldName) Then
                    vars(i.FieldName) = New VariableDef With {
                        .Name = i.FieldName,
                        .Length = i.EndPos - i.StartPos + 1,
                        .IsNumeric = i.IsNumeric,
                        .DecimalPos = If(String.IsNullOrEmpty(i.DecimalPos), 0, Integer.Parse(i.DecimalPos))
                    }
                End If
            End If
        Next

        ' From Calc Specs (Result fields often define new variables)
        Dim mathOps = {"ADD", "SUB", "MULT", "DIV", "Z-ADD", "SQRT", "MVR"}
        For Each c In _parser.CalcSpecs
            If Not String.IsNullOrWhiteSpace(c.ResultField) Then
                Dim isNumeric = Not String.IsNullOrWhiteSpace(c.DecimalPos) OrElse mathOps.Contains(c.Opcode)
                If Not vars.ContainsKey(c.ResultField) Then
                    vars(c.ResultField) = New VariableDef With {
                        .Name = c.ResultField,
                        .Length = If(c.FieldLength > 0, c.FieldLength, 15),
                        .IsNumeric = isNumeric,
                        .DecimalPos = If(String.IsNullOrEmpty(c.DecimalPos), 0, Integer.Parse(c.DecimalPos))
                    }
                ElseIf isNumeric Then
                    ' Force existing variable to numeric if used in math
                    vars(c.ResultField).IsNumeric = True
                End If
            End If
        Next

        Return vars
    End Function
End Class

Public Class VariableDef
    Public Property Name As String
    Public Property Length As Integer
    Public Property IsNumeric As Boolean
    Public Property DecimalPos As Integer
End Class
