/*
 * Generated by RPG2C Transpiler
 * Using RPG Runtime Library v1.0
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "rpg_runtime.h"
#include "rpg_file.h"
#include "rpg_data.h"

// --- Indicators ---
bool IND[100] = {false};
bool IN_LR = false;
bool IN_1P = true;
bool IN_MR = false;
bool IN_L[10] = {false};
#define IN_L1 IN_L[1] 
#define IN_L2 IN_L[2] 
#define IN_L3 IN_L[3] 
#define IN_L4 IN_L[4] 
#define IN_L5 IN_L[5] 
#define IN_L6 IN_L[6] 
#define IN_L7 IN_L[7] 
#define IN_L8 IN_L[8] 
#define IN_L9 IN_L[9] 

// --- Program Variables ---
char MSG1[6] = {0};
char MSG2[6] = {0};
char MSG3[7] = {0};
// --- Control Level Buffers ---

// --- Subroutines ---
void SUB1() {
    strcpy(MSG3, "INSIDE");
    // EXCPT (External Output) unsupported in simplified generator
}

int main(int argc, char** argv) {
    // Initialize RPG runtime
    rpg_init();

    if (argc < 2) {
        printf("Usage: %s <CONSOLE> \n", argv[0]);
        return 1;
    }

    FILE* CONSOLE = fopen(argv[1], "w");
    if (!CONSOLE) { printf("Failed to open CONSOLE\n"); return 1; }

    bool firstRecord = true;

    // --- 1P Header Processing ---
    IN_1P = true;

    // --- Main Logic Cycle ---
    {
        IN_LR = true;
        // Detail Calculations
        strcpy(MSG1, "START");
        SUB1();
        strcpy(MSG2, "END");
        IN_LR = true;
        fprintf(CONSOLE, "%*s%-*s", -4, "", 5, MSG1);
        fprintf(CONSOLE, "%*s%-*s", -4, "", 5, MSG2);
        fprintf(CONSOLE, "%*s%-*s", -5, "", 6, MSG3);
        fprintf(CONSOLE, "\n");
    }

    // --- Final LR Cycle ---
    IN_LR = true;
    // Total Calculations
    // Total Output
    if (CONSOLE) fclose(CONSOLE);

    // Cleanup RPG runtime
    rpg_cleanup();
    return 0;
}

