/*
 * Generated by RPG2C Transpiler
 * Using RPG Runtime Library v1.0
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "rpg_runtime.h"
#include "rpg_file.h"
#include "rpg_data.h"

// --- Indicators ---
bool IND[100] = {false};
bool IN_LR = false;
bool IN_1P = true;
bool IN_MR = false;
bool IN_L[10] = {false};
#define IN_L1 IN_L[1] 
#define IN_L2 IN_L[2] 
#define IN_L3 IN_L[3] 
#define IN_L4 IN_L[4] 
#define IN_L5 IN_L[5] 
#define IN_L6 IN_L[6] 
#define IN_L7 IN_L[7] 
#define IN_L8 IN_L[8] 
#define IN_L9 IN_L[9] 

// --- Program Variables ---
double NUM1 = 0.0;
double NUM2 = 0.0;
double RES = 0.0;
// --- Control Level Buffers ---

// --- Subroutines ---
int main(int argc, char** argv) {
    // Initialize RPG runtime
    rpg_init();

    if (argc < 3) {
        printf("Usage: %s <INPUT> <OUTPUT> \n", argv[0]);
        return 1;
    }

    FILE* INPUT = fopen(argv[1], "r");
    if (!INPUT) { printf("Failed to open INPUT\n"); return 1; }
    FILE* OUTPUT = fopen(argv[2], "w");
    if (!OUTPUT) { printf("Failed to open OUTPUT\n"); return 1; }

    char recordBuf[90];
    char lineIn[1024];
    bool firstRecord = true;

    // --- 1P Header Processing ---
    IN_1P = true;

    // --- Main Logic Cycle ---
    while (fgets(lineIn, sizeof(lineIn), INPUT)) {
        // Prepare fixed-length buffer from line
        memset(recordBuf, ' ', sizeof(recordBuf));
        int len = strlen(lineIn);
        while(len > 0 && (lineIn[len-1] == '\n' || lineIn[len-1] == '\r')) len--;
        strncpy(recordBuf, lineIn, (len > 80) ? 80 : len);
        recordBuf[80] = 0;
        IN_1P = false;
        // Check for Level Breaks

        if (!firstRecord && (
            IN_L1 || IN_L2 || IN_L3 || IN_L4 || IN_L5 || IN_L6 || IN_L7 || IN_L8 || IN_L9 || IN_LR
        )) {
            // --- Total Calculations ---

            // --- Total Output ---
        }
        for(int i=1; i<10; i++) IN_L[i] = false;

        // Extract Input Fields
        {
            char tmp[6]; strncpy(tmp, recordBuf + 0, 5); tmp[5] = 0;
            NUM1 = atof(tmp);
        }
        {
            char tmp[6]; strncpy(tmp, recordBuf + 5, 5); tmp[5] = 0;
            NUM2 = atof(tmp);
        }

        // --- Detail Calculations ---
        RES = NUM1 + NUM2;

        // --- Detail Output ---
            fprintf(OUTPUT, "%*s%-*.*f", -5, "", 6, 0, RES);
            fprintf(OUTPUT, "%*s%s", -9, "", "HELLO WORLD");
            fprintf(OUTPUT, "\n");
        firstRecord = false;
        if (IN_LR) break;
    }

    // --- Final LR Cycle ---
    IN_LR = true;
    // Total Calculations
    // Total Output
    if (INPUT) fclose(INPUT);
    if (OUTPUT) fclose(OUTPUT);

    // Cleanup RPG runtime
    rpg_cleanup();
    return 0;
}

