/*
 * Generated by RPG2C Transpiler
 * Using RPG Runtime Library v1.0
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "rpg_runtime.h"
#include "rpg_file.h"
#include "rpg_data.h"

// --- Indicators ---
bool IND[100] = {false};
bool IN_LR = false;
bool IN_1P = true;
bool IN_MR = false;
bool IN_L[10] = {false};
#define IN_L1 IN_L[1] 
#define IN_L2 IN_L[2] 
#define IN_L3 IN_L[3] 
#define IN_L4 IN_L[4] 
#define IN_L5 IN_L[5] 
#define IN_L6 IN_L[6] 
#define IN_L7 IN_L[7] 
#define IN_L8 IN_L[8] 
#define IN_L9 IN_L[9] 

// --- Program Variables ---
double NUM1 = 0.0;
double NUM2 = 0.0;
double SUM = 0.0;
double DIFF = 0.0;
double PROD = 0.0;
double QUOT = 0.0;
double SQROOT = 0.0;
double ROUND1 = 0.0;
// --- Control Level Buffers ---

// --- Subroutines ---
int main(int argc, char** argv) {
    // Initialize RPG runtime
    rpg_init();

    if (argc < 2) {
        printf("Usage: %s <REPORT> \n", argv[0]);
        return 1;
    }

    FILE* REPORT = fopen(argv[1], "w");
    if (!REPORT) { printf("Failed to open REPORT\n"); return 1; }

    bool firstRecord = true;

    // --- 1P Header Processing ---
    IN_1P = true;
    fprintf(REPORT, "%*s%s", 27, "", "CULATION TEST");
    fprintf(REPORT, "\n");

    // --- Main Logic Cycle ---
    {
        IN_LR = true;
        // Detail Calculations
        NUM1 = 100;
        NUM2 = 25;
        SUM = NUM1 + NUM2;
        DIFF = NUM1 - NUM2;
        PROD = NUM1 * NUM2;
        if (NUM2 != 0) QUOT = NUM1 / NUM2;
        SQROOT = rpg_sqrt(NUM1);
        ROUND1 = NUM1 + 0.555;
        IND[5] = (NUM1 > NUM2);
        IND[15] = (NUM1 < NUM2);
    }

    // --- Final LR Cycle ---
    IN_LR = true;
    // Total Calculations
    // Total Output
    if (REPORT) fclose(REPORT);

    // Cleanup RPG runtime
    rpg_cleanup();
    return 0;
}

